# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_auto_20170312_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementresource',
            old_name='resource',
            new_name='resource_files',
        ),
        migrations.AddField(
            model_name='achievementresource',
            name='resource_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
