# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_auto_20170312_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementresource',
            name='resource_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
