# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_auto_20170312_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_data', models.DateTimeField(auto_created=True)),
                ('resource_type', models.IntegerField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.Achievements')),
            ],
            options={
                'db_table': 'achievement_resources',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resource/%Y/%m/%d/')),
                ('achievement_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.AchievementResources')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('achievement_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.AchievementResources')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.RemoveField(
            model_name='achievementresource',
            name='achievement',
        ),
        migrations.DeleteModel(
            name='AchievementResource',
        ),
    ]
